; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "YousefStore"
#define MyAppVersion "1.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "Facture.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{54D21F3D-4247-4E60-844F-359E90A30DF7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\hp\Documents\GitHub\YousefStore\releases
OutputBaseFilename=YousefStorSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\ClosedXML.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\ClosedXML.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\ClosedXML.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Configuration.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\DocumentFormat.OpenXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\DocumentFormat.OpenXml.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\EntityFramework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\EntityFramework.SqlServer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\EntityFramework.SqlServer.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\EntityFramework.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\EnvDTE.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\EnvDTE.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\ExcelNumberFormat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\ExcelNumberFormat.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Facture.application"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Facture.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Facture.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Facture.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Facture.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\JetBrains.Annotations.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\JetBrains.Annotations.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.WinForms.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.WinForms.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.Wpf.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.Wpf.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\LiveCharts.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\MetroFramework.Design.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\MetroFramework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\MetroFramework.Fonts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.Bcl.HashCode.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.Bcl.HashCode.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.ReportViewer.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.ReportViewer.DataVisualization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.ReportViewer.ProcessingObjectModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.ReportViewer.WebDesign.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.ReportViewer.WebForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Microsoft.SqlServer.Types.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\SixLabors.Fonts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\SixLabors.Fonts.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\stdole.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Buffers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Data.SQLite.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Data.SQLite.EF6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Data.SQLite.Linq.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Data.SQLite.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.IO.FileSystem.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.IO.Packaging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Numerics.Vectors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Runtime.CompilerServices.Unsafe.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.ValueTuple.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.ValueTuple.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\System.Windows.Forms.Ribbon35.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\Tulpep.NotificationWindow.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\zxing.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\zxing.presentation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\zxing.presentation.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\zxing.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\x64\SQLite.Interop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projet Visual Studio\PointVenteSoft_Yousef_Store\Facture\bin\Release\AutoUpdater.NET.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
; Start Menu shortcut with custom icon
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\logostoreyousef.ico"; WorkingDir: "{app}"

; Desktop shortcut with custom icon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\logostoreyousef.ico"; Tasks: desktopicon; WorkingDir: "{app}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

